choco install -y firacode 
choco install -y cascadiacode
choco install -y firacodenf

choco install -y vscode
choco install -y irfanview
choco install -y lockhunter
choco install -y microsoft-windows-terminal
choco install -y notepadplusplus
choco install -y irfanviewplugins
choco install -y firefox
choco install -y jabra-direct
choco install -y sumantrapdf
choco install -y unifying
choco install -y yubico-authenticator
choco install -y winscp
choco install -y spotify
choco install -y virtualbox
#choco install -y signal
choco install -y everything
choco install -y vlc
choco install -y 7zip
choco install -y anaconda3

choco install -y git
choco install -y docker-desktop
choco insatll -y docker-cli
choco install -y terraform
choco install -y psqlodbc
choco install -y aws-vault
choco install -y awscli
choco install -y azure-cli
